before_install:  
  - brew update
  - brew install sdl2
script:  
  - xcodebuild -project "HelloWorld.xcodeproj" -scheme "HelloWorld" -destination "platform=iOS Simulator,name=iPhone X,OS=11.0" clean build

language: swift  
osx_image: xcode9  
xcode_project: HelloWorld.xcodeproj  
xcode_scheme: HelloWorld  
xcode_sdk: iphonesimulator9.2  
